
INSERT INTO teams (name, base, team_chief) VALUES
('Alfa Romeo Racing ORLEN', 'Hinwil, Switzerland', 'Frédéric Vasseur'),
('Scuderia AlphaTauri Honda', 'Faenza, Italy', 'Franz Tost'),
('Scuderia Ferrari Mission Winnow', 'Maranello, Italy', 'Mattia Binotto'),
('Haas F1 Team', 'Kannapolis, United States', 'Guenther Steiner'),
('McLaren F1 Team', 'Woking, United Kingdom', 'Andreas Seidl'),
('Mercedes-AMG Petronas F1 Team', 'Brackley, United Kingdom', 'Toto Wolff'),
('BWT Racing Point F1 Team', 'Silverstone, United Kingdom', 'Otmar Szafnauer'),
('Aston Martin Red Bull Racing', 'Milton Keynes, United Kingdom', 'Christian Horner'),
('Renault DP World F1 Team', 'Enstone, United Kingdom', 'Cyril Abiteboul'),
('ROKiT Williams Racing', 'Grove, United Kingdom', 'Frank Williams');

INSERT INTO `drivers` (`id`, `name`, `biography`, `image`, `team_id`, `country`, `podiums`, `points`, `world_championships`, `highest_race_finish`, `highest_grid_position`, `date_of_birth`, `place_of_birth`) VALUES
(1, 'Alexander Albon', '<p>He’s the matador from Madrid racing royalty.</p>\r\n<p>Entering F1’s Bull Ring paired alongside Max Verstappen at Toro Rosso in 2015, Sainz quickly showed his fighting spirit. A tenacious racer, Sainz puts the car on the edge as he hustles his way through the pack. No wonder he’s earned the nickname Chilli.</p>', 'alexander_albon.jpg', 8, 'Thailand', 0, 92, 0, 4, 5, '1996-03-23', 'London, England'),
(3, 'Valtteri Bottas', '<p>Learning his craft on Finnish roads of ice and snow, he was born to be a Grand Prix racer.</p>\r\n<p>Bottas explains that if you can drive on the frozen roads of his homeland then you can drive anywhere. Then there’s the Finnish mentality –reserved, diligent and calm the fast lane of F1 doesn’t faze him.</p>', 'valtteriBottas.jpg', 6, 'Finland', 45, 1289, 0, 1, 1, '1989-08-28', 'Nastola, Finland'),
(4, 'Pierre Gasly', '<p>If there’s one man who knows how big a rollercoaster ride an F1 driver’s career can be, it’s Pierre Gasly!</p>\r\n<p>The flying Frenchman was called up to make his 2017 debut in Malaysia in place of Daniil Kvyat and, after proving his mettle, he was named a Toro Rosso driver the following year.  A further 21 races into his fledgling career, Gasly was moved up again – this time to replace Red Bull big gun Daniel Ricciardo.</p>', 'pierre_gasly.jpg', 2, 'France', 1, 124, 0, 2, 4, '1996-02-07', 'Rouen, France'),
(5, 'Lewis Hamilton', '<p>‘Still I Rise’ – these are the words emblazoned across the back of Lewis Hamilton’s helmet and tattooed across his shoulders, and ever since annihilating expectations with one of the greatest rookie performances in F1 history in 2007, that’s literally all he’s done: risen to the top of the all-time pole positions list ahead of his hero Ayrton Senna, surged into second place in the wins column behind only the inimitable Michael Schumacher, and surpassed the legendary Sir Jackie Stewart for the most championship titles by a British driver.</p>', 'lewis_hammilton.jpg', 6, 'United Kingdom', 151, 3431, 6, 1, 1, '1985-01-07', 'Stevenage, England'),
(6, 'Daniel Ricciardo', '<p>The self-styled “Honey Badger” is fuzzy on the outside and feisty on the inside. Drivers beware because behind Ricciardo’s laidback persona and big grin is a razor-sharp racer with a bite.</p>\r\n<p>The Australian combines all-out speed with impressive race craft. Never afraid to push to the limits if it means pulling off a pass, Ricciardo is a proven race-winner for Red Bull, capable of consistently finishing at the business end of the championship table.</p>', 'daniel_ricciardo.jpg', 9, 'Australia', 29, 1040, 0, 1, 1, '1989-07-01', 'Perth, Australia'),
(7, 'Max Verstappen', '<p>He’s Max by name, and max by nature.</p><p>Arriving as Formula 1’s youngest ever competitor at just 17 years old, Verstappen pushed his car, his rivals and the sport’s record books to the limit. The baby-faced Dutchman with the heart of a lion took the Toro Rosso – and then the Red Bull – by the horns with his instinctive racing style.</p>', 'max_verstappen.jpg', 8, 'Netherlands', 31, 948, 0, 1, 1, '1997-09-30', 'Hasselt, Belgium'),
(8, 'Carlos Sainz', '<p>He’s the matador from Madrid racing royalty.</p>\r\n<p>Entering F1’s Bull Ring paired alongside Max Verstappen at Toro Rosso in 2015, Sainz quickly showed his fighting spirit. A tenacious racer, Sainz puts the car on the edge as he hustles his way through the pack. No wonder he’s earned the nickname Chilli.</p>', 'carlos_sainz.jpg', 5, 'Spain', 1, 267, 0, 3, 5, '1994-09-01', 'Madrid, Spain');